name: timecard
version: '0.1.0-SNAPSHOT'
source-code: https://github.com/Stephen-Hamilton-C/timecard
license: GPL-3.0
#icon: "icon.png"
summary: Simple commandline time tracking program, written in Kotlin Native
description: |
  timecard is a command line time tracking program
  written by a developer, for developers.
  Quick syntax allows time tracking to be easy, while also being customizable.
  Supports quarter-hour rounding, 24-hour time, and automatic cleanup.
  Written in Kotlin Native, for rapid fast response.
base: core18
apps:
  timecard-kt:
    command: $SNAP/timecard
    environment:
      XDG_CONFIG_HOME: "$SNAP_USER_DATA/"
      XDG_DATA_HOME: "$SNAP_USER_COMMON/"
parts:
  timecard-kt:
    plugin: gradle
    gradle-options: [buildNoExtension]
    gradle-output-dir: build/bin/native/releaseExecutable/
    source: https://github.com/Stephen-Hamilton-C/timecard.git
    #source-tag: v$SNAPCRAFT_PROJECT_VERSION
    #source-branch: <branch>
    source-branch: main
    #override-prime: |
    #  snapcraftctl prime
    #  rm -vf usr/lib/jvm/java-*-openjdk-*/lib/security/blacklisted.certs
    #override-build: |
    #  sudo ln -s /usr/bin/python3 /usr/bin/python
    #  snapcraftctl build
    #stage-packages:
    #  - default-jre-headless
    #build-packages:
    #  - python3
confinement: strict
